import type { Metadata } from "next";
import React from "react";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import { Providers } from "./providers";
import Backdrop from "@/components/Backdrop";
import NavBar from "@/components/NavBar";
import { Theme } from "@radix-ui/themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Theme>
            <main className="relative w-screen h-screen overflow-x-hidden">
              <NavBar />
              <Backdrop />
              {children}
            </main>
          </Theme>
        </Providers>
      </body>
    </html>
  );
}
